pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'globaldigitalheritage/arches-3d:$(build.buildId)'

steps:
- powershell: |
    if ("$env:BUILD_SOURCEBRANCHNAME" -e "master") {
      Write-Host("##vso[task.setvariable variable=IMAGE_VERSION]$env:BUILD_BUILDNUMBER")
    }
    elseif ("$env:BUILD_SOURCEBRANCHNAME" -e "master-test") {
      Write-Host("##vso[task.setvariable variable=IMAGE_VERSION]$env:BUILD_BUILDNUMBER-test")
    }
    else {
      # The special version part cannot exceed 20 characters, and cannot start with numbers
      $PreReleasePostFix = "$env:BUILD_SOURCEBRANCHNAME"
      if ($PreReleasePostFix.length -gt 20) {
          $PreReleasePostFix = $PreReleasePostFix.substring(0, 20)
      }
      Write-Host("##vso[task.setvariable variable=IMAGE_VERSION]$env:BUILD_BUILDNUMBER-$PreReleasePostFix")  
    }
    Write-Host("Image version [$(IMAGE_VERSION)])
  displayName: Resolve image version

- script: docker login -u $(dockerId) -p $(dockerPassword)
  displayName: 'docker login'

- script: docker-compose -f docker-compose-azure-pipelines.yml build arches
  displayName: 'docker-compose build'

- script: docker-compose -f docker-compose-azure-pipelines.yml run arches
  displayName: 'docker-compose tests'

- script: docker-compose -f docker-compose-azure-pipelines.yml push arches
  displayName: 'docker-compose push'
