pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'globaldigitalheritage/arches-3d:$(build.buildId)'

steps:
- task: Docker@1
  displayName: Login
  inputs:
    containerregistrytype: 'Dockerregistry'
    dockerRegistryEndpoint: 'docker_hub'
    command: login

- script: docker-compose -f docker-compose-azure-pipelines.yml build arches
  displayName: 'docker-compose build'

- script: docker-compose -f docker-compose-azure-pipelines.yml run arches
  displayName: 'docker-compose tests'

- script: docker-compose -f docker-compose-azure-pipelines.yml push arches
  displayName: 'docker-compose push'