pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'globaldigitalheritage/arches-3d:$(build.buildId)'

steps:
- script: docker login -u $(dockerId) -p $(dockerPassword)
  displayName: 'docker login'

- script: docker-compose -f docker-compose-azure-pipelines.yml build arches
  displayName: 'docker-compose build'

- script: docker-compose -f docker-compose-azure-pipelines.yml run arches
  displayName: 'docker-compose tests'

- script: docker-compose -f docker-compose-azure-pipelines.yml push arches
  displayName: 'docker-compose push'
