version: '3.3'

services:
  arches:
    container_name: arches
    image: globaldigitalheritage/arches-3d:master
    restart: always
    command: run_arches
    volumes:
      - arches-log:/web_root/arches_3d/arches_3d/logs
      - arches-static:/static_root
      - arches-uploadedfiles:/web_root/arches_3d/arches_3d/uploadedfiles
    environment:
      ARCHES_PROJECT: arches_3d
      INSTALL_DEFAULT_GRAPHS: False
      INSTALL_DEFAULT_CONCEPTS: False
      PGUSERNAME: postgres
      PGPASSWORD: postgres
      PGDBNAME: arches
      PGHOST: db
      PGPORT: 5432
      COUCHDB_HOST: couchdb
      COUCHDB_PORT: 5984
      COUCHDB_USER: admin
      COUCHDB_PASS: password
      ESHOST: elasticsearch
      ESPORT: 9200
      ELASTICSEARCH_PREFIX: arches_3d
      DJANGO_MODE: DEV
      DJANGO_DEBUG: True
      DOMAIN_NAMES: localhost
      TZ: EST
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch

  db:
    container_name: db
    image: mdillon/postgis:9.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-log:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: EST
    ports:
      - '5432:5432'

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.2
    restart: always
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      TZ: EST
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet

  elasticsearch2:
    container_name: elasticsearch2
    image: elasticsearch:5.2
    restart: always
    volumes:
      - elasticsearch-data2:/usr/share/elasticsearch/data
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.zen.ping.unicast.hosts: elasticsearch
      TZ: EST
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

volumes:
  arches-log:
  arches-static:
  arches-uploadedfiles:
  postgres-data:
  postgres-log:
  elasticsearch-data:
  elasticsearch-data2:

networks:
  esnet:
