version: '2'
services:

    arches:
      image: globaldigitalheritage/arches-3d:$(RELEASE_ARTIFACTS_ARCHES_3D_BUILD_TEST_BUILDNUMBER)-test
      command: run_arches
      volumes:
        - arches-log:/web_root/arches_3d/arches_3d/logs
        - arches-static:/static_root
      environment:
        - ARCHES_PROJECT=arches_3d
        - INSTALL_DEFAULT_GRAPHS=False
        - INSTALL_DEFAULT_CONCEPTS=False
        - PGUSERNAME=postgres
        - PGPASSWORD=postgres
        - PGDBNAME=arches
        - PGHOST=example.postgres.database.azure.com
        - PGPORT=5432
        - COUCHDB_HOST=couchdb
        - COUCHDB_PORT=5984
        - COUCHDB_USER=example
        - COUCHDB_PASS=example
        - ESHOST=example
        - ESPORT=9200
        - ELASTICSEARCH_PREFIX=arches_3d
        - DJANGO_MODE=PROD
        - DJANGO_DEBUG=False
        - AZURE_ACCOUNT_NAME=example
        - AZURE_ACCOUNT_KEY=example
        - AZURE_SSL=True
        - DOMAIN_NAMES=example.com
        - TZ=EST
      ports:
        - '8000:8000'

    nginx:
      image: vmeijer/nginx-proxy:1.2.3b
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - arches-static:/www/static
        - letsencrypt-acme-challenge:/var/www
        - letsencrypt:/etc/letsencrypt
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=strict-https
        - LOCAL_PROXY_HOST=arches
        - LOCAL_PROXY_PORT=8000
        - DOMAIN_NAMES=example.com
        - PUBLIC_MODE=False
        - STATIC_URL=/media
        - TZ=EST
      depends_on:
        - arches

    letsencrypt:
      image: vmeijer/letsencrypt-client:1.1
      volumes:
        - letsencrypt-acme-challenge:/var/www
        - letsencrypt:/etc/letsencrypt
        - letsencrypt-log:/var/log/letsencrypt
      command: get_certificate
      environment:
        - MODE=regular
        - LETSENCRYPT_EMAIL=example@example.com
        - DOMAIN_NAMES=example.com
        - PRODUCTION_MODE=True
        - PERSISTENT_MODE=True
        - TZ=EST
      depends_on:
        - nginx

volumes:
    arches-log:
    arches-static:
    letsencrypt:
    letsencrypt-log:
    letsencrypt-acme-challenge: